### PR TITLE
Fix library for the newer AGP

### PR DESCRIPTION
**Pull request by kamgurgul**
Newer versions of the Android Gradle Plugin requires namespace parameter

### CODE REVIEW

**Comment by AngeloAvv** [comment]
Do we have an ETA for this?

**Comment by fryette** [comment]
@AngeloAvv I suggest using it from PR by ref link, as I'm not maintaining it for long time

**Comment by fryette** [comment]
Ok, I will try to publish it this week

**Comment by pkonstantinov9** [comment]
looking forward for this update)

**Comment by omegasoft7** [comment]
@fryette Do you have any estimations when you are going to release this? I see that it is not release yet: https://pub.dev/packages/webview_cookie_manager

Or Am I missing anything here?

**Pull request merged**
